logging:
  level:
    root: WARN
logging:
  level:
    com:
      ruminderhub: DEBUG

logging:
  group:
    tomcat: 
     - org.apache.catalina
     - org.apache.coyote
     - org.apache.tomcat
logging:
  level:
    tomcat: INFO

database: app_develop
